### ISSUE TITLE
Problem loading TexMod textures

### ISSUE THREAD

**Issue by Mumblecrustt** [gwdevhub/gwlauncher#77]
I don't know if its related to the launcher, but I'm having an issue loading a custom texmod .tpf file with the new version of the launcher.

It loads Cartography Made Easy just fine. I can load my custom .tpf with the original version of TexMod, and with uMod and it used to work with the launcher. I've tried packaging it as a .zip, which also used to work but no longer does. I've tried using the account settings options to manually select the mod to no avail.

**Comment by DubbleClick** [comment]
Download the gMod.dll file from https://github.com/gwdevhub/gMod/releases/tag/v1.5.8.0 and place it in the gw launcher folder.

**Comment by Mumblecrustt** [comment]
Thanks for the quick reply. Did not fix my issue, I had a gMod.dll that i overwrote with this new one that you linked.

**Comment by Mumblecrustt** [comment]
Release 13 loads both of my .tpf files

**Comment by Mumblecrustt** [comment]
Github doesn't support .tpf uploads. I created the .tpf with Texmod - it only replaces two textures, 0x1FFF408d and 0x43FDAAC6 - I can load the package with Texmod, so the file is built correctly. 
[ahk_cues_black.zip](https://github.com/gwdevhub/gwlauncher/files/13533873/ahk_cues_black.zip)
rename .zip to .tpf - if that works

**Comment by DubbleClick** [comment]
Thanks, I will see to fix it for the next release.
