### ISSUE TITLE
Updating not working after GW2 Patch

### ISSUE THREAD

**Issue by Anthr0po1d** [gwdevhub/gwlauncher#78]
I have an issue with the GW Launcher since the last patch for GW2. When opening it asks to update the local.dat as usual but then gets stuck when updating the file. It looks like this: 

![image](https://github.com/gwdevhub/gwlauncher/assets/156421771/ff434e56-98ad-4595-9c06-7ee9c2b9b38f)

I cannot seem to get past this point and also cannot start the account manually via the launcher. Any advice?

**Comment by BearsMan** [comment]
GW Launcher doesn't support Guild Wars 2, if only works for Guild Wars 1. This issue should be closed, as nothing can be done.

**Comment by DubbleClick** [comment]
you want the gw2 launcher repo, this is gw1 launcher like bears explained
