### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by Tinte030** [gwdevhub/gwlauncher#79]
After download and starting the Guild Wars Launcher, it is asking me for a Master Passwort or something it was called like..  

So I don’t have any idea what to type in!?This can’t be any of my passwords so help please could not find it!

**Comment by DubbleClick** [comment]
It sets whatever you enter the first time as your password and requires you to enter it every time you start gw launcher.

If you don't want to use a password, close gw launcher, open Settings.json with a text editor and change "Encrypted" from true to false. Then delete Accounts.json and start gw launcher again.
