### ISSUE TITLE
Linux wine

### ISSUE THREAD

**Issue by GnomeBeans** [gwdevhub/gwlauncher#81]
Has anyone got this working on linux? I was able to get the app to run and even boot the game but never could get the .tpf file loaded for my custom UI.

**Comment by DubbleClick** [comment]
Some folks probably got it to work, but since gw, gwlauncher and gmod are all exclusively windows applications, I can't help you with figuring it out. Last I heard someone did it with Lutris, not Wine.

**Comment by Xyphis0** [comment]
Looks like version 14.1 is the latest functional release on wine (As long as .NET 6 runtimes are installed with winetricks).

Not sure why but later versions will silently crash on wine with .NET 8 Desktop runtimes installed.

**Comment by DubbleClick** [comment]
Interesting. 15.x versions have the .NET runtime bundled. Probably a wine bug and not related to gw launcher.

**Comment by Xyphis0** [comment]
You're probably right. All the same though, if it helps, when I try to run it using the Bash terminal Lutris provides I get the following:

Failed to load System.Private.CoreLib.dll (error code 0x8007046C)
Path: Z:\mnt\xyphis\Games\PC\Guild Wars\drive_c\Program Files\Guild Wars\GWLauncher\System.Private.CoreLib.dll
Error message:
Failed to create CoreCLR, HRESULT: 0x8007046C

**Comment by DubbleClick** [comment]
It might help the people maintaining Wine, but there's nothing I can do about it.

**Comment by GnomeBeans** [comment]
> You're probably right. All the same though, if it helps, when I try to run it using the Bash terminal Lutris provides I get the following:
> 
> Failed to load System.Private.CoreLib.dll (error code 0x8007046C) Path: Z:\mnt\xyphis\Games\PC\Guild Wars\drive_c\Program Files\Guild Wars\GWLauncher\System.Private.CoreLib.dll Error message: Failed to create CoreCLR, HRESULT: 0x8007046C

Similar error code here https://bugs.winehq.org/show_bug.cgi?id=56358

**Comment by ChthonVII** [comment]
Helpfully, the likely bug in the windows application (i.e. gwlauncher) that causes that error code is explained here: https://bugs.winehq.org/show_bug.cgi?id=56122#c1

> Application creates a placeholder using VirtualAlloc2/VirtualFree/MapViewOfFile3 and probably by mistake passes not 64k aligned addresses and offsets to MapViewOfFile3.

**Comment by DubbleClick** [comment]
Definitely not. These are WinAPI methods that you do not directly call in C#. Either it's a .NET problem (0.01% chance), or it's an emulation/translation problem (99.99% chance).
[GW Launcher Framework Dependent.zip](https://github.com/user-attachments/files/16626167/GW.Launcher.Framework.Dependent.zip)

This version will likely work, compiled framework dependent, not self contained.

**Comment by ChthonVII** [comment]
> This version will likely work, compiled framework dependent, not self contained.

New and different fatal error, so that's progress.

> 0128:err:eventlog:ReportEventW L"Application: GWLauncherFrameworkDependent.exe\n"
> 0128:err:eventlog:ReportEventW L"CoreCLR Version: 8.0.23.53103\n"
> 0128:err:eventlog:ReportEventW L".NET Version: 8.0.0\n"
> 0128:err:eventlog:ReportEventW L"Description: The process was terminated due to an unhandled exception.\n"
> 0128:err:eventlog:ReportEventW L"Exception Info: System.IO.FileLoadException: Could not load file or assembly 'GW Launcher, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Access denied.\r\n"
> 0128:err:eventlog:ReportEventW L"File name: 'GW Launcher, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'\r\n"
> 0128:err:eventlog:ReportEventW L" ---> System.UnauthorizedAccessException: Access denied. (0x80070005 (E_ACCESSDENIED))\n"
> 0128:fixme:advapi:DeregisterEventSource (CAFE4242) stub
> wine: Unhandled exception 0xe0434352 in thread 128 at address 7B642677 (thread 0128), starting debugger...

Not super clear to me what's trying to load what here.

Maybe possibly related, I vaguely recall toolbox having an issue what it tried to download its stuff to someplace it could not, then died trying to open them.

**Comment by DubbleClick** [comment]
https://github.com/gwdevhub/gwlauncher/releases

I've added a framework dependent build to the release pipeline. Fact is, the error lies within wine and not the application code as it works just fine on windows. I have no intentions of promising full wine/proton/lutris or other compatibility layer support - for one, because I do not control bugs within them and second, because I personally have zero use for linux installations with a gui.

**Comment by GnomeBeans** [comment]
Thanks to everyone who helped troubleshoot!

 Here's what fixed it:

    System: Lutris 64-bit prefix with dotnet 8 installed x86.
    
    Wine: ge-8-26 dont use this! Doesn't work. Switching to proton and then back will work but that might mess with prefix. The UWU proton 9.02 crashes when you right click. Until UWU is updated to newer wine I suggest using kron4ek wine vanilla build 9.15. I get through protonup. The only negative is borderless fullscreen only takes up half the screen. Change the resolution to fullscreen and then back to borderless or just select native option as borderless seems to do that anyway.
    
    Token Error: Set Guild Wars to run as administrator from the launcher settings.
    
    Launcher: Is located in Guild Wars root directory.
    
    Mods:
        Make sure gMod.dll is in Guild Wars root directory.
        Add gMod.dll as a native library in winecfg (or possibly Lutris). This was not needed with kron4ek 9.15
        Enable "use mods from plugins folder" in the launcher.
        Create a "plugins" folder in the Guild Wars root directory. Put mods here numbered like the readme.

This fixed the McPatch process handle error and mods are now working.

**Comment by GnomeBeans** [comment]
Further testing. Even though the above works and it seems to be resolved in newer version of wine the solution causes the camera in game to jump around which is not normal behavior from wine-ge. Since lutris is no longer receiving those updates I think the only choice we have is to wait for a newer uwu proton that supports the wine version where the right click menu is working without crashes.

**Comment by henderkes** [comment]
I would go one step further and change it to this, for gaming specifically:

> Up until now I've been using Linux. Don't do that everything is harder that way.
