### ISSUE TITLE
GW Launcher starts but exits after entering password

### ISSUE THREAD

**Issue by Blackdead** [gwdevhub/gwlauncher#86]
The new version 15 and 15.1 versions start up and ask for the password but exit after entering the password.
The version 14.1 works fine.
I don't get any error but a friend have the same problem (Windows 10/11) with the new versions.

**Comment by DubbleClick** [comment]
thank you for the report, I will look at it tomorrow

**Comment by StyxenZ** [comment]
For some additional context, here is the error from the Application log in Event Viewer:
```
Application: GW_Launcher.exe
CoreCLR Version: 8.0.524.21615
.NET Version: 8.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: SetCompatibleTextRenderingDefault must be called before the first IWin32Window object is created in the application.
   at System.Windows.Forms.Application.SetCompatibleTextRenderingDefault(Boolean defaultValue)
   at GW_Launcher.Program.Main()
```
